#ifndef __PLATFORM_CONFIG_H_
#define __PLATFORM_CONFIG_H_

#define STDOUT_IS_16550
#define STDOUT_BASEADDR XPAR_AXI_UART16550_0_BASEADDR

#define PRESCALE_REG XPAR_I2C_MASTER_TOP_0_BASEADDR
#define CMD_REG (XPAR_I2C_MASTER_TOP_0_BASEADDR + 1)
#define TRANSMIT_REG (XPAR_I2C_MASTER_TOP_0_BASEADDR + 2)
#define RECEIVE_REG (XPAR_I2C_MASTER_TOP_0_BASEADDR + 3)
#define ADDR_REG (XPAR_I2C_MASTER_TOP_0_BASEADDR + 4)
#define STATUS_REG (XPAR_I2C_MASTER_TOP_0_BASEADDR + 5)

#define X_AXIS_REG_1 0x32
#define X_AXIS_REG_2 0x33
#define Y_AXIS_REG_1 0x34
#define Y_AXIS_REG_2 0x35
#define Z_AXIS_REG_1 0x36
#define Z_AXIS_REG_2 0x37

#endif
